version: '3.3'

services:
    postgresql:
        image: postgres:13
        environment:
            - POSTGRES_DB=e_commerce_db
            - POSTGRES_USER=kevin_zav
            - POSTGRES_PASSWORD=kevin_zav_44_12
        ports:
            - '5432:5432'
        volumes:
            - ./postgres_data:/var/lib/postgresql/data

    pgadmin:
        image: dpage/pgadmin4
        environment:
            - PGADMIN_DEFAULT_EMAIL=root@admin.com
            - PGADMIN_DEFAULT_PASSWORD=root
        ports:
            - "5050:80"
